name: meallog
description: "MealLog - yemek gunlugu ve beslenme kaydi."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.1
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
